export const gifsMock = [
  {
    id: "zKRlxWqdP4NTok3Ppl",
    title: "Dragon Ball GIF by Toei Animation",
    url: "https://media4.giphy.com/media/v1.Y2lkPTQ4ZTMwMDdhcGVmY3NkMTIzM3h1NjF2YzY1eThudWVrc2pudHZleXJwb3R3OWlvYiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/zKRlxWqdP4NTok3Ppl/giphy.gif",
    width: 500,
    height: 360,
  },
  {
    id: "WOb8EeFziTQNE02WXs",
    title: "Dragon Ball Super GIF by Toei Animation",
    url: "https://media0.giphy.com/media/v1.Y2lkPTQ4ZTMwMDdhcGVmY3NkMTIzM3h1NjF2YzY1eThudWVrc2pudHZleXJwb3R3OWlvYiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/WOb8EeFziTQNE02WXs/giphy.gif",
    width: 540,
    height: 304,
  },
  {
    id: "aAbax5anloMNk6TSP9",
    title: "Dragon Ball GIF by Toei Animation",
    url: "https://media2.giphy.com/media/v1.Y2lkPTQ4ZTMwMDdhcGVmY3NkMTIzM3h1NjF2YzY1eThudWVrc2pudHZleXJwb3R3OWlvYiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/aAbax5anloMNk6TSP9/giphy.gif",
    width: 540,
    height: 294,
  },
  {
    id: "977YesTjNfQC7vQiph",
    title: "Dragon Ball GIF by Toei Animation",
    url: "https://media0.giphy.com/media/v1.Y2lkPTQ4ZTMwMDdhcGVmY3NkMTIzM3h1NjF2YzY1eThudWVrc2pudHZleXJwb3R3OWlvYiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/977YesTjNfQC7vQiph/giphy.gif",
    width: 498,
    height: 278,
  },
  {
    id: "lPwZcFRMGOFPO",
    title: "goku GIF",
    url: "https://media0.giphy.com/media/v1.Y2lkPTQ4ZTMwMDdhcGVmY3NkMTIzM3h1NjF2YzY1eThudWVrc2pudHZleXJwb3R3OWlvYiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/lPwZcFRMGOFPO/giphy.gif",
    width: 318,
    height: 231,
  },
  {
    id: "WUDGo9jYZzVt3DExhi",
    title: "Dragon Ball Z GIF by Toei Animation",
    url: "https://media1.giphy.com/media/v1.Y2lkPTQ4ZTMwMDdhcGVmY3NkMTIzM3h1NjF2YzY1eThudWVrc2pudHZleXJwb3R3OWlvYiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/WUDGo9jYZzVt3DExhi/giphy.gif",
    width: 360,
    height: 271,
  },
  {
    id: "19JSJ5ucu91R5D7a3w",
    title: "Dragon Ball Ultra Instinct GIF by Toei Animation",
    url: "https://media2.giphy.com/media/v1.Y2lkPTQ4ZTMwMDdhcGVmY3NkMTIzM3h1NjF2YzY1eThudWVrc2pudHZleXJwb3R3OWlvYiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/19JSJ5ucu91R5D7a3w/giphy.gif",
    width: 480,
    height: 270,
  },
  {
    id: "fmMdxlVwsCmTtA4V6a",
    title: "Dragon Ball 90S GIF by LnR motion",
    url: "https://media4.giphy.com/media/v1.Y2lkPTQ4ZTMwMDdhcGVmY3NkMTIzM3h1NjF2YzY1eThudWVrc2pudHZleXJwb3R3OWlvYiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/fmMdxlVwsCmTtA4V6a/giphy.gif",
    width: 480,
    height: 360,
  },
  {
    id: "17ytUBJ7boX5FHXmhg",
    title: "Dragon Ball Super GIF by Toei Animation",
    url: "https://media0.giphy.com/media/v1.Y2lkPTQ4ZTMwMDdhcGVmY3NkMTIzM3h1NjF2YzY1eThudWVrc2pudHZleXJwb3R3OWlvYiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/17ytUBJ7boX5FHXmhg/giphy.gif",
    width: 540,
    height: 304,
  },
  {
    id: "yhXPFygSaOuzmnq8tF",
    title: "Dragon Ball Super Black Goku GIF by Toei Animation",
    url: "https://media3.giphy.com/media/v1.Y2lkPTQ4ZTMwMDdhcGVmY3NkMTIzM3h1NjF2YzY1eThudWVrc2pudHZleXJwb3R3OWlvYiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/yhXPFygSaOuzmnq8tF/giphy.gif",
    width: 480,
    height: 274,
  },
];
